# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bastion < Formula
  desc "CLI for SSH bastion tunnel management"
  homepage "https://github.com/LipJ01/fly-ssh-bastion"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/LipJ01/fly-ssh-bastion/releases/download/v0.2.0/bastion_0.2.0_darwin_amd64.tar.gz"
      sha256 "de6fec9631c3d82302fb2da7381000b1f52cf0a32864223d14c1d2a348515612"

      def install
        bin.install "bastion"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/LipJ01/fly-ssh-bastion/releases/download/v0.2.0/bastion_0.2.0_darwin_arm64.tar.gz"
      sha256 "921c33ffe3fb9e2fe27bae661d80e0552d31af5a3670a21fb4fb3042b65ce925"

      def install
        bin.install "bastion"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/LipJ01/fly-ssh-bastion/releases/download/v0.2.0/bastion_0.2.0_linux_amd64.tar.gz"
      sha256 "6ede5eb54dd1b7ddb8aebaab5e7f530e9d561c45a71c70a7558b942dee9a2b12"
      def install
        bin.install "bastion"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/LipJ01/fly-ssh-bastion/releases/download/v0.2.0/bastion_0.2.0_linux_arm64.tar.gz"
      sha256 "1dffc05a950d870fb10fb2a6e2b19f14dc6c411fe05cee56c970759882db5b47"
      def install
        bin.install "bastion"
      end
    end
  end
end
