# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bastion < Formula
  desc "CLI for SSH bastion tunnel management"
  homepage "https://github.com/LipJ01/fly-ssh-bastion"
  version "0.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/LipJ01/fly-ssh-bastion/releases/download/v0.2.1/bastion_0.2.1_darwin_amd64.tar.gz"
      sha256 "9eb6577bddda1b63119d5e22c912eb0249afa2abf78dae39f863d620c84a1111"

      def install
        bin.install "bastion"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/LipJ01/fly-ssh-bastion/releases/download/v0.2.1/bastion_0.2.1_darwin_arm64.tar.gz"
      sha256 "031540f43ce8efe8f43969166f96aaf3c70b9436dc48185be72ac28fabc4827e"

      def install
        bin.install "bastion"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/LipJ01/fly-ssh-bastion/releases/download/v0.2.1/bastion_0.2.1_linux_amd64.tar.gz"
      sha256 "22ca96402beca32cc3396a1bf4d110f53205efbaebe3e3267a801b90f09afe8c"
      def install
        bin.install "bastion"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/LipJ01/fly-ssh-bastion/releases/download/v0.2.1/bastion_0.2.1_linux_arm64.tar.gz"
      sha256 "42e16efa82595778a58de7d106bff01eb18f9ee8e69bbd50483fcf763c204422"
      def install
        bin.install "bastion"
      end
    end
  end
end
