# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bastion < Formula
  desc "CLI for SSH bastion tunnel management"
  homepage "https://github.com/LipJ01/fly-ssh-bastion"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/LipJ01/fly-ssh-bastion/releases/download/v0.1.0/bastion_0.1.0_darwin_amd64.tar.gz"
      sha256 "a800ef1718d1f22015ddce304094cca0d958af9acb44346fad275401d03c83cf"

      def install
        bin.install "bastion"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/LipJ01/fly-ssh-bastion/releases/download/v0.1.0/bastion_0.1.0_darwin_arm64.tar.gz"
      sha256 "02055df5f6f55df1861f92e06d2861430fe8de9f36509a775a4c2518f2bbec70"

      def install
        bin.install "bastion"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/LipJ01/fly-ssh-bastion/releases/download/v0.1.0/bastion_0.1.0_linux_amd64.tar.gz"
      sha256 "7b6fd6405c590b25e7c299c18f5029f8d526e1dd2182a3acc7a96230c722bb96"
      def install
        bin.install "bastion"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/LipJ01/fly-ssh-bastion/releases/download/v0.1.0/bastion_0.1.0_linux_arm64.tar.gz"
      sha256 "6dbf632d6813db0c1ccb2e98b3e606be2e83bf22b0eaa2c16d49ea2d44eef4ff"
      def install
        bin.install "bastion"
      end
    end
  end
end
